language: node_js
sudo: required
before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/leafjs/leaf/${TRAVIS_BRANCH}/prepareTravis.sh)
install:
  - npm install -g codecov
  - npm install -g codeclimate-test-reporter
script:
  - npm test
  - codecov
after_script:
  - codeclimate-test-reporter < lcov.info
node_js:
  - "6"
  - "5"
  - "4"
env:
  - CXX=g++-4.8 CC=gcc-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - gcc-4.8
      - m4
      - flex
  code_climate:
    repo_token: 46d83d59992bcdc800fc5b7f22dce911bc64959a70e59f6396607c0cd6dbb026
cache:
  directories:
    - node_modules
